---
ConfigFile: ''
leftBarLinks: 
resourceLinks: 
disableKubeWatch: false
kubeWatchResyncInterval: 1800000000000
webfilesPath: "./pkg/sloop/webfiles"
bindAddress: ''
port: 8080
storeRoot: "./data"
maxLookBack: 1209600000000000
maxDiskMb: 32768
debugPlaybackFile: ''
debugRecordFile: ''
deletionBatchSize: 1000
mockBadger: false
disableStoreManager: false
cleanupFrequency: 1800000000000
keepMinorNodeUpdates: false
defaultNamespace: default
defaultKind: Pod
defaultLookback: 3h
context: ''
displayContext: ''
apiServerHost: ''
watchCrds: true
threshold for GC: 0.8
restoreDatabaseFile: ''
badgerDiscardRatio: 0.99
badgerVLogGCFreq: 60000000000
badgerMaxTableSize: 0
badgerLevelOneSize: 0
badgerLevSizeMultiplier: 0
badgerKeepL0InMemory: true
badgerVLogFileSize: 0
badgerVLogMaxEntries: 200000
badgerUseLSMOnlyOptions: true
badgerEnableEventLogging: false
badgerNumOfCompactors: 0
badgerSyncWrites: true
badgerVLogFileIOMapping: false
badgerVLogTruncate: true
enableDeleteKeys: false
