language: go

go:
  - 1.13.x

services:
  - docker

script:
  - go test ./...

before_deploy:
  - test -n "$TRAVIS_TAG" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  script: >
    if test -n "$GITHUB_TOKEN"; then
      curl -sfL https://git.io/goreleaser | sh -s -- release --rm-dist
    else
      curl -sfL https://git.io/goreleaser | sh -s -- release --rm-dist --skip-publish &&
      docker push "$TRAVIS_REPO_SLUG"
    fi
  on:
    tags: true