language: go

branches:
  except:
    - master
  only:
    - release
go:
  - 1.13.x

services:
  - docker

script:
  - go test ./...
  - curl -sfL https://git.io/goreleaser | sh -s -- check

before_deploy:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sfL https://git.io/goreleaser | sh -s -- release --rm-dist --skip-publish && docker push "$TRAVIS_REPO_SLUG"
  on:
    tags: true